version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - echo "Installing Chromedriver"
  
      # Install Ruby and the chromedriver-helper gem
      - yum install -y ruby
      - gem install chromedriver-helper
  
      # Use chromedriver-install script to install Chromedriver
      - chromedriver-install
  
      # Print the Chromedriver version for verification
      - chromedriver -v

  build:
    commands:
      - echo "Running Chromedriver version check"
      - chromedriver -v

artifacts:
  files: '**/*'
