version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - yum install -y libatk-bridge2.0-0 libatspi libxkbcommon0

build:
  commands:
    # Your build commands go here
    - pwd
    - whoami
    - uname -m
